# Tell Docker to use the latest python image 
FROM python:latest
# Run updates on apt, as is best practice
RUN apt update
# Install CVXOPT dependencies
RUN apt-get install -y python-dev-is-python3 build-essential libblas-dev liblapack-dev libsuitesparse-dev